### ISSUE TITLE
n1安装istore后首页没有变化

### ISSUE THREAD

**Issue by AbianTang** [wukongdaily/commonscript#1]
使用的的f的的n1固件，OpenWrt R23.08.18 (2023-08-18 16:34:23 by flippy) / LuCI Master (git-23.226.38647-7acf7ff)，3. 安装iStore应用商店及首页风格
第一次安装报错Collected errors:
 * opkg_download: Failed to download https://op.dllkids.xyz/packages/aarch64_cortex-a53/Packages.sig, wget returned 8.
 * opkg_download: Failed to download https://mirrors.cloud.tencent.com/lede/snapshots/targets/armvirt/64/packages/Packages.gz, wget returned 8.
第二次没有，以下为结尾，但是首页没有变化，istore显示，istore图标错误
Downloading https://istore.linkease.com/repo/aarch64_cortex-a53/nas/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/is_nas
Downloading https://istore.linkease.com/repo/all/compat/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/istore_compat
***********************************************************************
*      软路由基础工具箱(for Openwrt) v1.0        

openwrt截图   
https://xingmuxi.xyz/d/%E9%98%BF%E9%87%8C%E4%BA%91%E7%9B%98/public/20042911169213178.png?sign=okez27Q3pm8nYWoSHnM3s2dsjiltSkLV8SpYAARXUvI=:0

**Comment by wukongdaily** [comment]
你好，收到你的留言反馈。我打算试试你这个固件。你可以帮忙找到你刷机这个固件的下载地址吗。谢谢

**Comment by seensure98** [comment]
我用的是openwrt_s905d_n1_R23.08.18_k6.1.46-flippy-84+.7z  这个
脚本没报错，但是没有新界面（首页、网络向导）和istore商店

**Comment by AbianTang** [comment]
是的,出现的问题一致

2023 年 9 月 13 日星期三 20:38, seensure98 ***@***.***(mailto:2023 年 9 月 13 日星期三 20:38, seensure98 <<a href=)> 来信：

**Comment by wukongdaily** [comment]
嗯谢谢你们反馈。flippy的 5.15内核和6.1 的内核，我都测试了。确实有问题。iStore商店勉强可以。但是首页和网络向导不行。这个问题先open着，我抽时间在好好研究下。当时开发的时候用的supes的固件。

**Comment by wukongdaily** [comment]
目前我已经找到办法了。如图，已经修复了。我稍后提交代码。
![](https://github.com/wukongdaily/commonscript/blob/master/common/N1-flippy-like-iStoreOS.png?raw=true)

**Comment by seensure98** [comment]
收到，谢谢悟空大佬

**Comment by wukongdaily** [comment]
已修复。请重新执行脚本即可。
