### ISSUE TITLE
iStore里面安装软件，出现这个些内容。

### ISSUE THREAD

**Issue by lsvf0240** [wukongdaily/commonscript#14]
No page is registered at '/admin/system/opkg'.
If this url belongs to an extension, make sure it is properly installed.
If the extension was recently installed, try removing the /tmp/luci-indexcache file.

固件版本 | OpenWrt R23.06.08 (2023-06-08 21:00:03 by flippy) / LuCI Master (git-23.141.16773-28dd4b3)

内核版本 | 5.15.115-flippy-83+o

**Comment by wukongdaily** [comment]
请尝试一下新版本。
