### ISSUE TITLE
r68s安装无iStore商店

### ISSUE THREAD

**Issue by ryxiang** [wukongdaily/commonscript#15]
软路由：r68s
固件版本 QWRT R23.9.1 / LuCI Master (git-23.226.24689-eba8e8b)
内核版本 5.10.110
问题描述：
安装后，自动切换到了argone主题，但是并无iStore商店，多次安装，还是一样。安装系统调试必备工具，出现istore安装失败，固件不兼容

![image](https://github.com/wukongdaily/commonscript/assets/52651563/30f6521b-6b23-4cd6-ad4f-6ffd9eeca4fe)

![image](https://github.com/wukongdaily/commonscript/assets/52651563/b051d896-e3bb-4b6f-9bcc-31f9f8ad4a82)

**Comment by wukongdaily** [comment]
新版本已解决。请从新执行代码即可！执行后，建议退出网页，从新登录看看
