### ISSUE TITLE
x86_64安装后，自动切换到了argone主题，但是并无iStoreOS功能。

### ISSUE THREAD

**Issue by tyc502044421** [wukongdaily/commonscript#2]
固件版本    OpenWrt R21.8.6 GDQ v9.1[2021] Compiled by eSir / LuCI Master (git-21.238.35254-83494a9)
内核版本    5.4.132
问题描述：
     x86_64安装后，自动切换到了argone主题，但是并无iStoreOS功能。

iStoreOS主题安装前，已经安装过argone主题。
随后一键卸载iStoreOS主题，然后卸载掉原argone主题后，重新一键安装iStoreOS主题，问题依旧。

还有一个小问题，多次安装后在 固件版本 加的小标签 “with iStoreOS Style” 没有重置，也多次追加了。

![微信截图_20230925210326](https://github.com/wukongdaily/commonscript/assets/16531414/1660a7f7-7d5a-46c0-9240-438de3679e9f)

**Comment by wukongdaily** [comment]
非常好的反馈！图文并茂，感谢感谢。然后你用的这个版本稍微有点古老了。是否考虑一下先升级到eSir 2023的版本。https://drive.google.com/drive/folders/1KRnkJBo1EIwQ6B8IH3N8uMXTKh9AxIyD?usp=drive_link
然后追加字样这个我会抓紧解决。谢谢。

**Comment by tyc502044421** [comment]
> 非常好的反馈！图文并茂，感谢感谢。然后你用的这个版本稍微有点古老了。是否考虑一下先升级到eSir 2023的版本。https://drive.google.com/drive/folders/1KRnkJBo1EIwQ6B8IH3N8uMXTKh9AxIyD?usp=drive_link 然后追加字样这个我会抓紧解决。谢谢。

新版已测试，菜单有iStore商店显示，商店正常可以用，主页这些依然没有，其它就看图。
![微信图片_20230925211618](https://github.com/wukongdaily/commonscript/assets/16531414/cf2ea484-c033-47ac-9b03-4206f3e1637a)

**Comment by wukongdaily** [comment]
哦~ 那还真有点奇怪了，我再想想。奥对了刚才那个字符串重复的问题我修复了（已提交代码）。目前你固件和我相同，不过我是物理机安装。浏览器如果强制刷新，那个首页也出不来吗。

**Comment by tyc502044421** [comment]
> 哦~ 那还真有点奇怪了，我再想想。奥对了刚才那个字符串重复的问题我修复了（已提交代码）。目前你固件和我相同，不过我是物理机安装。浏览器如果强制刷新，那个首页也出不来吗。

重启、强制刷新、隐私模式 都试过，无效。

**Comment by wukongdaily** [comment]
新版本已解决。请从新执行代码即可！
