### ISSUE TITLE
安装时提示cannot verify raw.githubusercontent.com's certificate

### ISSUE THREAD

**Issue by colour008** [wukongdaily/commonscript#23]
具体错误为
root@OpenWrt:~# wget -O /tmp/drive-common.sh  https://raw.githubusercontent.com/wukongdail
y/commonscript/master/common/drive-common.sh && chmod +x /tmp/drive-common.sh  && /tmp/dri
ve-common.sh
--2023-11-11 18:01:32--  https://raw.githubusercontent.com/wukongdaily/commonscript/master/common/drive-common.sh
Resolving raw.githubusercontent.com... 0.0.0.0
Connecting to raw.githubusercontent.com|0.0.0.0|:443... connected.
ERROR: cannot verify raw.githubusercontent.com's certificate, issued by 'CN=OpenWrt,O=OpenWrt2a27e6ad,L=Unknown,ST=Somewhere,C=ZZ':
  Self-signed certificate encountered.
    ERROR: certificate common name 'OpenWrt' doesn't match requested host name 'raw.githubusercontent.com'.
To connect to raw.githubusercontent.com insecurely, use `--no-check-certificate'.
按照网上各种修改方法都无法解决包括修改host或者加 --no-check-certificate 参数等，麻烦猴哥看一下是什么情况。

**Comment by colour008** [comment]
自己摸索终于解决啦，好开心
![063E7542](https://github.com/wukongdaily/commonscript/assets/70709807/5ff94e4b-2c61-44e2-a723-dfd42dc174d3)
具体方法是，将猴哥的`common.sh`下载到本地，然后打开openwrt文件传输，将`common.sh`上传到路由器，然后ssh打开路由终端，先输入`cd \tmp\upload\`进入文件夹内，然后利用`ls`命令查看是否存在`common.sh`，如果存在，继续输入`chmod +x /tmp/upload/common.sh  && /tmp/upload/common.sh`，就可以加载脚本进入安装步骤啦！！！

**Comment by wukongdaily** [comment]
非常好 理解终于到位了。就是因为路由器本身无法访问到github文件导致的，所以最好的办法就是上传到路由器里 再执行。后面会考虑制作u盘版
