### ISSUE TITLE
证书问题

### ISSUE THREAD

**Issue by zht007** [wukongdaily/commonscript#24]
固件和主机型号如下
>

主机名 | QWRT
-- | --
主机型号 | CMCC RAX3000M
架构 | ARMv8 Processor rev 4 (v8l) x 2 (1300MHz, 72.1°C)
目标平台 | mediatek/mt7981
固件版本 | QWRT R23.9.1 / LuCI Master (git-23.226.24689-eba8e8b)
内核版本 | 5.4.250
本地时间 | Sun Nov 12 10:37:53 2023

>
错误信息如下：
```
--2023-11-12 10:31:40--  https://raw.githubusercontent.com/wukongdaily/commonscript/master/common/drive-common.sh

Resolving raw.githubusercontent.com... 0.0.0.0, ::
Connecting to raw.githubusercontent.com|0.0.0.0|:443... connected.
ERROR: cannot verify raw.githubusercontent.com's certificate, issued by 'CN=OpenWrt,O=OpenWrt3d485f52,L=Unknown,ST=Somewhere,C=ZZ':
  Self-signed certificate encountered.
    ERROR: certificate common name 'OpenWrt' doesn't match requested host name 'raw.githubusercontent.com'.
To connect to raw.githubusercontent.com insecurely, use `--no-check-certificate'.
```

**Comment by Lisang7** [comment]
N1一样这个代码

--2023-11-12 22:26:44--  https://raw.githubusercontent.com/wukongdaily/commonscript/master/common/common.sh
Resolving raw.githubusercontent.com... 0.0.0.0, ::
Connecting to raw.githubusercontent.com|0.0.0.0|:443... connected.
ERROR: cannot verify raw.githubusercontent.com's certificate, issued by 'CN=OpenWrt,O=OpenWrtc01b04d3,L=Unknown,ST=Somewhere,C=ZZ':
  Self-signed certificate encountered.
    ERROR: certificate common name 'OpenWrt' doesn't match requested host name 'raw.githubusercontent.com'.
To connect to raw.githubusercontent.com insecurely, use `--no-check-certificate'.

**Comment by colour008** [comment]
我也遇到同样的问题了。我用以下方法解决了:将猴哥的`common.sh`下载到本地，然后打开openwrt文件传输，将`common.sh`上传到路由器，然后`ssh`打开路由终端，先输入`cd \tmp\upload\`进入文件夹内，然后利用`ls`命令查看是否存在`common.sh`，如果存在，继续输入`chmod +x /tmp/upload/common.sh  && /tmp/upload/common.sh`，就可以加载脚本进入安装步骤啦！！！

**Comment by wukongdaily** [comment]
替换为cdn，已解决。
