### ISSUE TITLE
没有出现istore OS 风格

### ISSUE THREAD

**Issue by woni928** [wukongdaily/commonscript#8]
固件地址：
https://github.com/woni928/OpenWrt-N1-test3/releases/download/N1-my-1.2_20230928/openwrt_s905d_n1_R23.7.7_k5.4.257-flippy-85+o.img.gz

<img width="2123" alt="1" src="https://github.com/wukongdaily/commonscript/assets/28220733/e043f7b2-c7ff-4b79-9eb4-23ebcf6ca49d">

**Comment by wukongdaily** [comment]
收到，谢谢你的反馈。我刷一个检查一下。目前看来是quickstart 组件没有安装成功。

**Comment by wukongdaily** [comment]
新版本已解决。请从新执行代码即可！
